import { Course } from "./types";

export const COURSES = [
  {
    id: 1,
    name: "HTML & CSS",
    nr_videos: 120,
    nr_teachers: 2,
    views: 1500,
    price: 20,
    img_id: "course-1",
  },
  {
    id: 2,
    name: "Art of Photography",
    nr_videos: 50,
    nr_teachers: 3,
    views: 2100,
    price: 32,
    img_id: "course-2",
  },
  {
    id: 3,
    name: "React for Dummies",
    nr_videos: 33,
    nr_teachers: 1,
    views: 13901,
    price: 19,
    img_id: "course-3",
  },
  {
    id: 4,
    name: "UI/UX Basics",
    nr_videos: 110,
    nr_teachers: 5,
    views: 2999,
    price: 200,
    img_id: "course-4",
  },
  {
    id: 5,
    name: "Intro to C/C++",
    nr_videos: 70,
    nr_teachers: 4,
    views: 43133,
    price: 34,
    img_id: "course-1",
  },
  {
    id: 6,
    name: "Science of Psychology",
    nr_videos: 24,
    nr_teachers: 6,
    views: 12,
    price: 20,
    img_id: "course-2",
  },
  {
    id: 7,
    name: "Algorithms in Java",
    nr_videos: 35,
    nr_teachers: 7,
    views: 5334,
    price: 30,
    img_id: "course-3",
  },
] as Course[];
